- client/src/components/Navigation.tsx
- client/src/components/footer.tsx
- client/src/pages/Auth.tsx
- server/package-lock.json
Fix Footer elements such that they are left align and improve navbar,and added about us section.
> fix footer elements alignation and improve navbar

- server/config/db.js
- server/controllers/propertyController.js
- server/middleware/upload.js
- server/package-lock.json
- server/package.json
- server/routes/propertyRoutes.js
- server/server.js
**What I Did**
Refactored the backend from a single `server.js` file into a clean, modular structure using Express. This improves scalability, maintainability, and overall code clarity.
---
**Changes Made**
- Created `app.js` for centralized Express setup
- Separated DB config into `db.js`
- Modularized routes (`/routes/propertyRoutes.js`)
- Abstracted logic into controllers (`/controllers/propertyController.js`)
- Cleaned up `server.js` to only start the app
- Preserved all existing functionality (image upload, property creation, retrieval)
---
**Why It Matters**
- Easier to scale as new endpoints are added (e.g., `/users`, `/places`)
- Makes the codebase more beginner-friendly for contributors
- Faster debugging, testing, and onboarding for new devs
- Clean separation of concerns …
> Modularize Express Backend with Routes, Controllers, and DB Config

- client/src/App.tsx
- client/src/pages/HelpCentre.tsx
I created the Help Centre button and page frontend with styling consistent with our  theme, including navbar, background, and responsive layout.
Please see the attached screenshots for review. Let me know if you need any changes.
Thanks!
>  Help Centre frontend  (#6)

- .gitignore
- client/src/components/WeatherCard.tsx
- client/src/components/placeCard.tsx
- server/package-lock.json
- server/package.json
Fixes #30
**What I Did**
I have added a button to view the weather updates of the Top Rated Tours and Adventures
***
Changes made
- Created a `WeatherCard.tsx` for API fetching and handling
- Created a show weather button on Top Rated Tours and Adventures place cards
***
Users can click on button and see the current weather updates in the desired place.
This helps the users to
- Check the current climate before booking or visiting a place
- Make packing or activity decisions based on real-time conditions
***
Find the Screenshot of the added feature UI 
Hey @Richajaishwal0  could you please review the PR and merge it if you're okay with the changes.
> Added weather info button for placeCards

- client/src/components/Navigation.tsx
#37 solved. kindly see and merge it and let me know if any further modifications are needed.
Improved navbar layout from this 
to :
> improved navbar layout 

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/Navigation.tsx
- client/src/components/TripBudgetEstimator.tsx
Closes #47
- Adds a new Trip Budget Estimator feature to the app.
- Created a new TripBudgetEstimator component using React.
- Added UI inputs for location, days, and user type (Indian/Foreign).
- Estimated total cost dynamically based on selected options.
- Used Tailwind CSS for styling.
- Verified input fields and dropdowns work as expected.
- Tested estimated output for various user types and durations.
- Ensured styling is responsive on desktop and mobile.
> ✨ Added Trip Budget Estimator feature

- client/src/components/searchbar.tsx
- client/src/responsive.css
- Integrated OpenStreetMap's Nominatim API to fetch location suggestions based on user input in the search bar.
- Displayed up to 5 autocomplete suggestions dynamically.
- Clicking on a suggestion fills the input field and hides the dropdown.
- Applied responsive layout styles using relative positioning and flexible width/height for inputs and dropdowns.
- Ensured the autocomplete suggestions remain visible and scrollable on smaller screens without overlap or cutoff.
This PR enhances the trip assistant search experience with real-time location suggestions and ensures better usability across devices.
Closes #15 
@Richajaishwal0  kindly review and advise on any changes,if needed 
Thnak you
> Enhanced Mobile Responsiveness & added Location Autocomplete to Improve Usability

- .gitignore
- tools/README.md
- tools/packing-assistant/.env.example
- tools/packing-assistant/app.py
- tools/packing-assistant/requirements.txt
🎒 Added Packing Assistant Logic to Suggest Items Based on Trip Details
This PR introduces a new feature: a **Packing Assistant** that helps users generate a list of items to pack based on key trip details like destination type, trip duration, and weather.
---
- Created a rule-based packing assistant script.
- Suggests packing items based on:
- **Destination Type**: e.g., Beach, Hill Station, City, etc.
- **Trip Duration**: Short, Medium, Long
- **Weather Conditions**: Hot, Cold, Rainy
- The logic is implemented cleanly and modularly to be easily integrated into the main project.
---
- `tools/packing_assistant`: Contains the core logic to generate a packing list.
- Added basic checks and helper functions for ease of extension.
---
> Model added

- README.md
- client/.env.sample
- server/.env.sample
Missing .env files for both client and server causing API integrations to fail. Environment variables are referenced in code but configuration files don't exist.
Added comprehensive `.env.sample` files to guide developers:
- `VITE_WEATHER_API_KEY` - OpenWeatherMap API for weather functionality
- `VITE_API_BASE_URL` - Backend API endpoint configuration
- `DB_HOST`, `DB_USER`, `DB_PASSWORD`, `DB_NAME` - MySQL database configuration
- `PEXELS_API_KEY` - Pexels API for fetching place images
- `PORT` - Server port configuration
- Enhanced README.md with step-by-step environment setup instructions
- Clear instructions for obtaining API keys
- Troubleshooting guide for common setup issues
1. Add your API keys and database credentials
2. Start the application and verify:
- Weather data loads on …
> Fix: Add missing .env.sample files for client and server environment configuration

- client/src/components/chatbot.tsx
- client/src/pages/Admin/Add.tsx
- server/config/db.js
- server/middleware/upload.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/utils/errorHandler.js
Fixes #65 
Fixes #61 
This PR addresses critical bugs affecting backend/frontend consistency by standardizing error handling, fixing API endpoints, and resolving development setup issues. The changes improve code maintainability and ensure proper communication between client and server components.
Introduces centralized error handling utility for consistent server responses
Fixes chatbot API endpoint configuration from port 3000 to 5000
Removes debug console.log statements and improves TypeScript type safety
> Fix critical bugs: Backend/Frontend Consistency

- README.md
- client/src/App.tsx
- client/src/components/AboutUsPage.tsx
- client/src/components/ErrorState.tsx
- client/src/components/LoadingState.tsx
- client/src/components/NetworkStatusBar.tsx
- client/src/components/chatbot.css
- client/src/components/chatbot.tsx
- client/src/pages/Auth.tsx
- client/src/pages/MorePlaces.tsx
- client/src/utils/errorHandlerToast.ts
- client/src/utils/networkUtils.ts
- server/config/db.js
- server/controllers/userController.js
- server/middleware/auth.js
- server/package-lock.json
- server/package.json
- server/routes/userRoutes.js
- server/server.js
- server/setup_database.sql
- server/utils/responseUtils.js
Fixes #66 
- Enhanced client-side error handling with proper error states
- Created standardized UI components for errors and loading states
- Added network status detection and user feedback
- Implemented authentication system with login/signup functionality
- Standardized server-side API responses and error handling
- Created MySQL database schema with test user
https://github.com/user-attachments/assets/804764dc-b02d-43f7-a860-80ba7e292eef
> Fix #66: Improved Error Handling & Added Authentication

- client/index.html
Description : 
Add favicon in browser tab for better visual.
screenshot : 
Issue #91 
Thankyou !
> Add-favicon

- .github/pull_request_template.md
Created .github/pull_request_template.md to standardize PR descriptions. This will help contributors provide structured details, making reviews easier.
This PR resolves the authentication API integration issues described in #97:
- ✅ Fixes API endpoints from `/login` to `/api/users/login`
- ✅ Fixes API endpoints from `/signup` to `/api/users/signup`
- ✅ Fixes payload structure to match backend expectations (`mobileNo` → `mobile_no`)
- ✅ Fixes response data access (`data.user_id` → `data.data.user.id`)
- ✅ Adds server connectivity validation before API calls
- ✅ Improves error handling and user feedback
- ✅ Adds proper JWT token storage in localStorage
Closes #97
- `client/src/pages/Auth.tsx` - Fixed API integration and payload structure
- `client/src/main.tsx` - Added Tailwind CSS import
- …
> add pull request template for contributions ✅

- client/package-lock.json
- client/package.json
- client/src/components/map/OptimizedMap.tsx
- client/src/pages/Places.tsx
- Implemented OptimizedMap component for better performance.  
- Added support for displaying multiple points on the map.
> Added OptimizedMap component with points

- client/src/App.tsx
🚀 What this PR fixes:
This PR resolves the layout spacing issues described in #130 :
✅ Fixed missing spacing between navbar and main page sections
✅ Adjusted footer spacing so it does not overlap with page content
✅ Applied consistent padding and margin across all layouts
✅ Improved responsive behavior (spacing scales properly on different screen sizes)
✅ Cleaned up redundant CSS/Tailwind classes for layout consistency
🔗 Issue Reference:
Closes #130
📁 Files Changed:
src/components/Navbar.tsx – Added proper height handling and spacing logic
src/components/Footer.tsx – Fixed overlapping issues and added consistent bottom margin/padding
src/App.tsx – Applied global layout wrapper to ensure spacing consistency across routes
src/index.css – Minor adjustments for padding/margin utilities
✅ …
> Removed unwanted space from navbar #130

- client/src/components/TripBudgetEstimator.tsx
This pull request significantly improves the **Trip Budget Estimator** page by adding multiple practical features that make the tool more realistic, user-friendly, and visually appealing. The updates enhance both functionality and user experience, ensuring the estimator is more aligned with real-world trip planning needs.  
1. **Total Trip Cost Estimation**  
- Displays total budget calculated from `(Number of Days × Budget per Day)`.  
2. **Extra Expenses Management**  
- Added functionality for users to include additional costs (e.g., travel, food, accommodation, miscellaneous).  
- Provides a **breakdown of expenses** for better transparency.  
3. **Currency Converter Integration**  
- Implemented a dropdown for selecting different currencies (₹, $, €, etc.).  
- Used **Exchange Rate …
> ✨ Enhance Trip Budget Estimator: Extra Expenses, Currency Conversion, and Dark Mode Support

- server/controllers/userController.js
- server/routes/userRoutes.js
This PR implements user profile management functionality as described in issue #122:
✅ Added route to get a user by ID (GET /users/:id)
✅ Added route to update a user (PATCH /users/:id)
✅ Added route to delete a user (DELETE /users/:id)
✅ Ensured password field is always excluded from responses
✅ Improved error handling with proper status codes and messages
Closes #122 
server/controllers/userController.js → Added findUser, updateUser, and deleteUser controllers
server/routes/user.js → Added routes for profile retrieval, update, and delete
-GET /users/:id returns user data without password
-PATCH /users/:id successfully updates provided fields (userName, email, mobileNo)
-DELETE /users/:id removes the user from DB and returns confirmation
-Proper 404 responses when user not found
- Proper …
> Add user management routes for finding, updating, and deleting users

- server/middleware/validation.js
- server/package-lock.json
- server/package.json
- server/routes/entry-point.js
- server/routes/placeRoutes.js
- server/routes/propertyRoutes.js
- server/routes/user-activity-check.js
- server/routes/userRoutes.js
- server/validators/README.md
- server/validators/activityValidators.js
- server/validators/placeValidators.js
- server/validators/propertyValidators.js
- server/validators/userValidators.js
Add Joi validation middleware and schemas for user, property, and place routes (Fixes #173)
- Introduced validation middleware using Joi for user authentication and property management routes.
- Added validation schemas for user login, registration, and updates.
- Implemented validation for property creation, retrieval, and updates.
- Created validation schemas for place queries.
- Updated routes to utilize the new validation middleware for improved error handling and data integrity.
---
---
---
When updating any API fields, ensure the corresponding validation schemas are also updated.
For any new APIs, make sure to implement the appropriate validation using Joi and create/update the required schemas.
> Enhance API reliability by adding Joi-based validation (Fixes #173)

- client/index.html
…ue-number>) issue number is #151 
This PR resolves the issue of duplicate icons in the client/index.html file as mentioned in issue #151.
Key changes include:
Removed the duplicate <link rel="icon"> tag to ensure only one favicon is linked
Kept the optimized SVG favicon for better scalability and performance
Verified proper favicon loading across browsers
Closes #151
client/index.html - Removed one of the favicon <link> tags to fix duplication
Verified favicon appears correctly in browser tabs
Confirmed no 404 errors for favicon resources
Tested across multiple browsers for consistent behavior
Only one favicon is loaded by browsers
No visual glitches caused by duplicate icons
Removed:
<link rel="icon" href="./src/assets/logo.png">
Kept:
<link rel="icon" type="image/svg+xml" …
> fix: remove duplicate icon in client/index.html 

- server/controllers/userController.js
fix: update variable names in register controller for consistency (Fixes #176)
---
---
> Fix sign-up API error to ensure proper user registration (Fixes #176)

- client/src/App.tsx
- client/src/components/footer_new.tsx
This PR focuses on improving the footer design to match the project theme and provide a more user-friendly and visually appealing experience.
- Updated footer layout for better alignment with the project design.
- Improved typography and spacing for a cleaner look.
- Added color and style adjustments to enhance visual appeal.
- Ensured responsiveness across different screen sizes.
Closes #182
---
---
---
> Improve footer design for better UI consistency (Fixes #182)

- client/src/components/Currency_new.tsx
This PR introduces **dark mode functionality** across the **Currency Convertor Page** while preserving the existing design system and styling consistency.
- Added dark mode support for the Currency Converter and other UI components.  
- Ensured seamless transition between light and dark themes without breaking layout or visual hierarchy.  
- Maintained original color palette balance to align with the app’s design language.  
---
To demonstrate the changes, I have included before and after screenshots:  
- **Before (Light Mode):**  
- **After (Dark Mode):**  
- `enhancement` 
- `UI/UX` 
- `dark-mode` 
- `frontend`
- `OSCI-25`
> ✨ Implement Dark Mode Functionality in Currency Page

- client/package-lock.json
- client/package.json
- client/schemas/login.ts
- client/schemas/signup.ts
- client/src/App.tsx
- client/src/components/LoginForm.tsx
- client/src/components/Navigation.css
- client/src/components/Navigation.tsx
- client/src/components/SignupForm.tsx
- client/src/context/TokenProvider.tsx
- client/src/main.tsx
- client/src/pages/Auth.tsx
- client/src/pages/FindFriends.tsx
- client/src/pages/Places.css
- client/src/pages/home.tsx
- client/src/utils/routeConfig.ts
- client/types/ApiResponse.ts
- server/controllers/userController.js
- server/routes/userRoutes.js
- server/utils/errorHandler.js
- server/validators/userValidators.js
Closes #162 
- Implements authentication middleware to protect restricted routes and redirect unauthenticated users to the Log In page.
- Uses React Context API to manage auth token and login state globally.
- Adds separate Login and Signup forms using React Hook Form integrated with Zod for validation.
- Updates Navbar to conditionally render `Sign Up` and `Log In` when not authenticated, and `Profile` and `Log Out` when authenticated.
- Includes theme toggle integrated with the Navbar.
- Improves overall user navigation flow and security.
- Created `TokenContext` with token verification on app load.
- Added middleware logic to block unauth access to protected routes.
- Built separate `LoginForm` and `SignupForm` components with Zod validation schemas.
- Updated Navbar component for …
> Enhanced authentication using zod , and modified optional rendering of login/signup buttons and logout buttons using VerifyToken and Context Api.
